/**
 * `code-style/rust-format` adapter — the Rust family's formatter.
 *
 * `rustfmt` and `clippy` ship with the toolchain (and the emitted
 * devcontainer's `rust` feature already installs both), so like Go
 * this costs the project no new dependency. Unlike Go it *is*
 * configurable, via `rustfmt.toml`.
 *
 * rustfmt ignores `.editorconfig` — the request has been open since
 * 2018 and was closed unimplemented — so this file is a **co-render**
 * of the same {@link STYLE_MODEL} numbers rather than a reader of it.
 * Hand-editing one without the other drifts them apart, which is why
 * the emitted `.editorconfig` says so in its header.
 *
 * `style_edition` is pinned explicitly even though a 2024-edition
 * crate already defaults to it. RFC 3338 decoupled the *style*
 * edition from the *language* edition precisely so the two can move
 * independently; naming it here freezes today's formatting against a
 * future edition bump silently reflowing the whole tree.
 */

import { formatterAdapter, styleFor } from './code-style.js';
import type { Adapter } from '../../contract/composition.js';

export const RUST_FORMAT_ID = 'code-style/rust-format';

/** Target path of the emitted rustfmt configuration. */
export const RUSTFMT_TARGET = 'rustfmt.toml';

/** The style edition the emitted crates are formatted against. */
const STYLE_EDITION = '2024';

/** Renders `rustfmt.toml` from keel's style model. */
export function renderRustfmtConfig(): string {
  const style = styleFor('rust');
  return [
    '# Generated by keel from one style model, shared with .editorconfig.',
    '# rustfmt does not read .editorconfig, so these are a co-render of the',
    '# same numbers — change both, or re-run `keel add code-style --reapply`.',
    '',
    '# Pinned rather than inherited from the crate edition: RFC 3338 lets the',
    '# style edition move independently, and an implicit bump would reflow',
    '# every file at once.',
    `style_edition = "${STYLE_EDITION}"`,
    '',
    `max_width = ${style.lineWidth ?? 100}`,
    `tab_spaces = ${style.indentSize}`,
    `hard_tabs = ${style.indentStyle === 'tab'}`,
    'newline_style = "Unix"',
    '',
  ].join('\n');
}

export const rustFormatAdapter: Adapter = formatterAdapter(RUST_FORMAT_ID, ['lang.rust'], () => ({
  files: [{ path: RUSTFMT_TARGET, content: renderRustfmtConfig() }],
}));
