/**
 * `code-style/web-lint` adapter — the web family's `linter` dimension.
 *
 * The one family with **no** zero-dependency subset of this
 * vertical's scope. TypeScript has no wildcard-import syntax to
 * forbid (`import * as ns` is a namespace import, not the
 * bring-everything-into-scope kind Java/Kotlin/Rust have), which
 * removes one leg outright — but naming case and doc comments on
 * exported API both need a rule engine; `tsc` alone checks neither.
 * Checkstyle, detekt and golangci-lint are staged as a
 * separately-argued follow-up (`docs/verticals/code-style.md`), but
 * ESLint cannot be deferred the same way: `resolveVertical` requires
 * *every* declared dimension to be covered for *every* tag set, so
 * without a web adapter here the `linter` dimension could not be
 * added to `codeStyleVertical` at all without breaking every
 * TypeScript and web-components install. This ships now, scoped to
 * exactly the two legs that apply.
 *
 * Verified against real ESLint 10.8.1 + typescript-eslint 8.67.0 +
 * eslint-plugin-jsdoc 64.2.1 on a scratch workspace:
 * `@typescript-eslint/naming-convention` and `jsdoc/require-jsdoc`
 * both fire on a violating file and both exit clean on a compliant
 * one. `naming-convention` is deliberately unrestricted to exported
 * symbols — it applies repo-wide, the same reach Java/Kotlin/Rust's
 * naming rules have via the compiler — while `require-jsdoc` is
 * `publicOnly: true`, matching the binding spec's "public API only"
 * comments policy (`assets/project/AGENTS.md` §8).
 *
 * A direct `eslint .` invocation, not a `package.json` script: see
 * `linterCommandsFor` in `code-style.ts` for why `"lint"` is already
 * taken by `depcruise` on the modulith layouts. The config and the
 * three devDependencies are added unconditionally; no seed, since
 * nothing else emits `eslint.config.js`.
 */

import { linterAdapter } from './code-style.js';
import type { Adapter, Ctx } from '../../contract/composition.js';

export const WEB_LINT_ID = 'code-style/web-lint';

/** ESLint version added to the workspace root. */
export const ESLINT_VERSION = '^10.8.1';

/** `typescript-eslint` — the parser + plugin + configs meta-package. */
export const TYPESCRIPT_ESLINT_VERSION = '^8.67.0';

/** eslint-plugin-jsdoc — gates exported symbols on a doc comment. */
export const ESLINT_PLUGIN_JSDOC_VERSION = '^64.2.1';

const ESLINT_CONFIG_TARGET = 'eslint.config.js';
const PACKAGE_JSON_TARGET = 'package.json';

/**
 * Renders `eslint.config.js` — flat config, the only shape ESLint 10
 * accepts. `typescript-eslint`'s non-type-checked `recommended` preset
 * keeps this fast (no `parserOptions.project`, so it does not need to
 * resolve every workspace package's own `tsconfig.json`), which matters
 * because this is a CI-only check with no hook budget to protect it
 * from.
 */
export function renderEslintConfig(): string {
  return `import tseslint from 'typescript-eslint';
import jsdoc from 'eslint-plugin-jsdoc';

// Generated by keel. Naming case applies repo-wide, matching how
// Java/Kotlin/Rust enforce it via the compiler; doc-comment coverage
// is scoped to exported (public) API, matching the binding spec's
// "public API only" comments policy.
export default tseslint.config(
  { ignores: ['**/dist/**', '**/build/**', '**/coverage/**', '**/*.min.js'] },
  tseslint.configs.recommended,
  {
    plugins: { jsdoc },
    rules: {
      '@typescript-eslint/naming-convention': [
        'error',
        { selector: 'default', format: ['camelCase'] },
        { selector: 'typeLike', format: ['PascalCase'] },
        { selector: 'variable', format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'property', format: null },
        { selector: 'import', format: null },
      ],
      'jsdoc/require-jsdoc': [
        'error',
        {
          publicOnly: true,
          require: { FunctionDeclaration: true, ClassDeclaration: true, MethodDefinition: true },
        },
      ],
    },
  },
);
`;
}

/**
 * Adds ESLint and its two rule packages to the workspace root
 * manifest. Mirrors `addPrettierToPackageJson`: parses and
 * re-serialises key-sorted so the patch is idempotent, and never
 * overwrites a devDependency the project already pins.
 */
export function addEslintToPackageJson(existing: string): string {
  const pkg = JSON.parse(existing) as Record<string, unknown>;
  const devDeps = { ...((pkg.devDependencies as Record<string, string> | undefined) ?? {}) };
  let changed = false;

  const wanted: Record<string, string> = {
    eslint: ESLINT_VERSION,
    'typescript-eslint': TYPESCRIPT_ESLINT_VERSION,
    'eslint-plugin-jsdoc': ESLINT_PLUGIN_JSDOC_VERSION,
  };
  for (const [name, version] of Object.entries(wanted)) {
    if (devDeps[name] === undefined) {
      devDeps[name] = version;
      changed = true;
    }
  }
  if (!changed) return existing;

  pkg.devDependencies = sortKeys(devDeps);
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

/** Key-sorted copy, so a re-apply cannot reorder the map. */
function sortKeys(map: Readonly<Record<string, string>>): Record<string, string> {
  return Object.fromEntries(Object.entries(map).sort(([a], [b]) => a.localeCompare(b)));
}

export const webLintAdapter: Adapter = linterAdapter(
  WEB_LINT_ID,
  ['lang.typescript'],
  (_ctx: Ctx) => ({
    files: [{ path: ESLINT_CONFIG_TARGET, content: renderEslintConfig() }],
    patches: [{ target: PACKAGE_JSON_TARGET, apply: addEslintToPackageJson }],
  }),
);
