/**
 * `code-style/web-format` adapter — Prettier for both TypeScript
 * stacks and the web-components SPA.
 *
 * Predicated on `lang.typescript` alone, so one adapter serves
 * `ts-cli`, `ts-http` and `web-components` — the same shape
 * `ci/ts-pipeline` already uses, and for the same reason: the
 * package manager and entrypoint are dials read from tags, never
 * grounds for a second adapter.
 *
 * **Prettier rather than Biome**, deliberately. Biome is faster and
 * is the reasonable default for a greenfield TypeScript service, but
 * its HTML formatter is still experimental — and `web-components` is
 * a framework-free SPA, which is the one stack here that is mostly
 * HTML, in `.html` files and in template literals. One formatter
 * across all three stacks beats a faster one on two of them.
 *
 * Prettier reads `.editorconfig` natively for `end_of_line`,
 * `indent_style`, `indent_size` and `max_line_length`, but
 * `.prettierrc` *overrides* it. The emitted config therefore spells
 * the same numbers rather than omitting them: relying on the
 * fallback would make the effective style depend on which file
 * Prettier happened to find, and the explicit values keep the two in
 * agreement by construction.
 */

import { formatterAdapter, styleFor } from './code-style.js';
import type { Adapter, Ctx } from '../../contract/composition.js';

export const WEB_FORMAT_ID = 'code-style/web-format';

/** Prettier version added to the workspace root. */
export const PRETTIER_VERSION = '^3.9.6';

const PRETTIERRC_TARGET = '.prettierrc.json';
const PRETTIERIGNORE_TARGET = '.prettierignore';
const PACKAGE_JSON_TARGET = 'package.json';

/**
 * Renders `.prettierrc.json` from keel's style model.
 *
 * The non-layout options match what keel itself uses, so a
 * contributor moving between keel and a keel-scaffolded project
 * meets one house style rather than two.
 */
export function renderPrettierConfig(): string {
  const style = styleFor('web');
  const config = {
    semi: true,
    singleQuote: true,
    trailingComma: 'all',
    arrowParens: 'always',
    endOfLine: 'lf',
    useTabs: style.indentStyle === 'tab',
    tabWidth: style.indentSize,
    printWidth: style.lineWidth ?? 100,
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

/** Renders `.prettierignore` — generated and vendored trees only. */
export function renderPrettierIgnore(): string {
  return [
    '# Generated by keel.',
    'node_modules/',
    'dist/',
    'build/',
    'coverage/',
    '*.min.js',
    'pnpm-lock.yaml',
    'package-lock.json',
    '',
  ].join('\n');
}

/**
 * Adds Prettier and the `format` / `format:check` scripts to the
 * workspace root manifest.
 *
 * Parses and re-serialises at 2-space with a trailing newline — the
 * shape Prettier itself produces — so the patch is idempotent and
 * key-stable, matching `addOtelDependencies` in `ts-observability`.
 * Existing scripts are never overwritten: a project that already
 * defines `format` keeps its own.
 */
export function addPrettierToPackageJson(existing: string): string {
  const pkg = JSON.parse(existing) as Record<string, unknown>;
  const devDeps = { ...((pkg.devDependencies as Record<string, string> | undefined) ?? {}) };
  const scripts = { ...((pkg.scripts as Record<string, string> | undefined) ?? {}) };
  let changed = false;

  if (devDeps.prettier === undefined) {
    devDeps.prettier = PRETTIER_VERSION;
    changed = true;
  }
  if (scripts.format === undefined) {
    scripts.format = 'prettier --write .';
    changed = true;
  }
  if (scripts['format:check'] === undefined) {
    scripts['format:check'] = 'prettier --check .';
    changed = true;
  }
  if (!changed) return existing;

  pkg.devDependencies = sortKeys(devDeps);
  pkg.scripts = sortKeys(scripts);
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

/** Key-sorted copy, so a re-apply cannot reorder the map. */
function sortKeys(map: Readonly<Record<string, string>>): Record<string, string> {
  return Object.fromEntries(Object.entries(map).sort(([a], [b]) => a.localeCompare(b)));
}

export const webFormatAdapter: Adapter = formatterAdapter(
  WEB_FORMAT_ID,
  ['lang.typescript'],
  (_ctx: Ctx) => ({
    files: [
      { path: PRETTIERRC_TARGET, content: renderPrettierConfig() },
      { path: PRETTIERIGNORE_TARGET, content: renderPrettierIgnore() },
    ],
    patches: [{ target: PACKAGE_JSON_TARGET, apply: addPrettierToPackageJson }],
  }),
);
