/**
 * The asdf provider record — the second manager on the dial, and the
 * one whose native file the wider ecosystem reads: `.tool-versions`
 * is asdf's own format, understood by mise too, so choosing asdf
 * here leaves a file that keeps working if the project later moves
 * managers.
 *
 * asdf names tools by *plugin*, and a few plugin names differ from
 * the block's vocabulary (`go` → `golang`, `node` → `nodejs`, `jdk`
 * → `java`); the JDK spelling additionally qualifies the block's
 * major with a distribution, registered in
 * `assets/composition/version-pins.json` (`asdf-java-distribution`)
 * the way mise's is. Installing is two steps: add the plugin for
 * every tool (tolerating "already added", asdf's way of saying the
 * step was a no-op), then `asdf install`, which reads the rendered
 * file.
 *
 * **One fidelity caveat, deliberately on record.** asdf documents
 * `.tool-versions` as a lockfile: it wants concrete versions, and
 * forbids `latest` there. Where the block pins a *major* — `jdk 25`,
 * `node 22` — the rendered line is a prefix, which asdf resolves
 * only for plugins that accept one. Resolving prefixes through the
 * manager (`asdf latest <plugin> <prefix>`) needs an engine step
 * that runs before rendering, which is N.4's business; until then
 * mise, whose resolver takes prefixes natively, stays the default.
 */

import type { ProcessResult } from '../../contract/ports/process-runner.js';
import {
  TOOLCHAIN_TOOLS,
  type ToolchainNeed,
  type ToolchainTool,
} from '../../contract/toolchain.js';
import type { ProviderInvocation, SpelledNeed, ToolchainProvider } from './provider.js';

/** The JDK distribution asdf spellings qualify the block's major with. */
const JDK_DISTRIBUTION = 'temurin';

/** Tools whose asdf plugin is not named after the tool. */
const PLUGIN_NAMES: Partial<Record<ToolchainTool, string>> = {
  jdk: 'java',
  go: 'golang',
  node: 'nodejs',
};

const CONFIG_HEADER = `# Generated by keel ('keel toolchain install') from the toolchain block in
# .claude/.keel-manifest.json — edits here are overwritten on the next run.
# After a keel upgrade: 'keel add toolchain --reapply', then re-install.
`;

function spell(need: ToolchainNeed): SpelledNeed {
  const name = PLUGIN_NAMES[need.tool] ?? need.tool;
  return need.tool === 'jdk'
    ? { name, version: `${JDK_DISTRIBUTION}-${need.version}` }
    : { name, version: need.version };
}

/** Whether an installed version answers the requested one. */
function answers(installed: string, requested: string): boolean {
  return installed === requested || installed.startsWith(`${requested}.`);
}

/** The asdf record. */
export const asdfProvider: ToolchainProvider = {
  id: 'asdf',
  label: 'asdf — .tool-versions, the format mise reads too',
  covers: TOOLCHAIN_TOOLS,
  spell,
  render(needs) {
    const entries = needs
      .map(spell)
      .map((spelled) => `${spelled.name} ${spelled.version}\n`)
      .join('');
    return [{ path: '.tool-versions', content: `${CONFIG_HEADER}\n${entries}` }];
  },
  probe: { command: 'asdf', args: ['--version'] },
  install(needs) {
    const plugins: ProviderInvocation[] = [...new Set(needs.map((need) => spell(need).name))].map(
      (plugin) => ({
        command: 'asdf',
        args: ['plugin', 'add', plugin],
        // asdf reports an already-added plugin as a failure; the
        // install that follows is where a genuinely missing plugin
        // surfaces.
        tolerateFailure: true,
      }),
    );
    return [...plugins, { command: 'asdf', args: ['install'] }];
  },
  status: { command: 'asdf', args: ['list'] },
  parseStatus(result: ProcessResult, spelled) {
    // A non-zero exit is data here, not a failure: `asdf list` says
    // "No plugins installed" that way, which is precisely "nothing is
    // satisfied" rather than "the manager could not be asked".
    let plugin: string | undefined;
    const installed = new Map<string, string[]>();
    for (const line of result.stdout.split('\n')) {
      if (line.trim().length === 0) continue;
      if (/^\S/.test(line)) {
        plugin = line.trim();
        installed.set(plugin, []);
        continue;
      }
      // Indented: one installed version, the active one marked '*'.
      if (plugin !== undefined) installed.get(plugin)?.push(line.trim().replace(/^\*/, ''));
    }
    return new Map(
      spelled.map((need) => [
        need.name,
        (installed.get(need.name) ?? []).some((version) => answers(version, need.version)),
      ]),
    );
  },
  bootstrap:
    'asdf is not installed.\n' +
    'Bootstrap it with:  brew install asdf   (or your package manager)\n' +
    '(other install methods: https://asdf-vm.com/guide/getting-started.html)',
};
