/**
 * The asdf provider record — the second manager on the dial, and the
 * one whose native file the wider ecosystem reads: `.tool-versions`
 * is asdf's own format, understood by mise too, so choosing asdf
 * here leaves a file that keeps working if the project later moves
 * managers.
 *
 * asdf names tools by *plugin*, and a few plugin names differ from
 * the block's vocabulary (`go` → `golang`, `node` → `nodejs`, `jdk`
 * → `java`); the JDK spelling additionally qualifies the block's
 * major with a distribution, registered in
 * `assets/composition/version-pins.json` (`asdf-java-distribution`)
 * the way mise's is. Installing is two steps: add the plugin for
 * every tool (tolerating "already added", asdf's way of saying the
 * step was a no-op), then `asdf install`, which reads the rendered
 * file.
 *
 * **`.tool-versions` is a lockfile, and this record treats it as
 * one.** asdf documents the format as wanting concrete versions and
 * forbids `latest` there, while the block pins a *major* for the JDK
 * and for Node. So the record declares a
 * {@link ToolchainProvider.resolve}: before anything is rendered the
 * engine asks asdf itself — `asdf latest <plugin> <prefix>` — and the
 * file gets `java temurin-25.0.4+7` where the block says `jdk 25`
 * (roadmap N.6). keel never invents the patch half; when asdf cannot
 * be asked, the version already in `.tool-versions` stands if it
 * answers the prefix, and only when there is nothing to stand on does
 * the prefix render, loudly, as it did before.
 */

import type { ProcessResult } from '../../contract/ports/process-runner.js';
import {
  TOOLCHAIN_TOOLS,
  type ToolchainNeed,
  type ToolchainTool,
} from '../../contract/toolchain.js';
import type {
  ProviderInvocation,
  ResolvedSpellings,
  SpelledNeed,
  ToolchainProvider,
  VersionResolution,
} from './provider.js';

/** The JDK distribution asdf spellings qualify the block's major with. */
const JDK_DISTRIBUTION = 'temurin';

/** asdf's own file, which it reads from the project root. */
const CONFIG_PATH = '.tool-versions';

/** Tools whose asdf plugin is not named after the tool. */
const PLUGIN_NAMES: Partial<Record<ToolchainTool, string>> = {
  jdk: 'java',
  go: 'golang',
  node: 'nodejs',
};

const CONFIG_HEADER = `# Generated by keel ('keel toolchain install') from the toolchain block in
# .claude/.keel-manifest.json — edits here are overwritten on the next run.
# After a keel upgrade: 'keel add toolchain --reapply', then re-install.
`;

function spell(need: ToolchainNeed): SpelledNeed {
  const name = PLUGIN_NAMES[need.tool] ?? need.tool;
  return need.tool === 'jdk'
    ? { name, version: `${JDK_DISTRIBUTION}-${need.version}` }
    : { name, version: need.version };
}

/** Whether an installed version answers the requested one. */
function answers(installed: string, requested: string): boolean {
  return installed === requested || installed.startsWith(`${requested}.`);
}

/** The version a `.tool-versions` already carries for a plugin. */
function configured(name: string, existing: string): string | undefined {
  for (const line of existing.split('\n')) {
    const [plugin, version] = line.trim().split(/\s+/);
    if (plugin === name && version !== undefined) return version;
  }
  return undefined;
}

/**
 * How asdf makes a prefix concrete — see the module doc. A spelling
 * is a prefix until its numeric part names three components: asdf
 * plugins publish `temurin-25.0.4+7`, `22.21.0`, `1.24.3`, so `25`,
 * `22` and `1.24` are all prefixes, while the wrapper pins the block
 * already carries in full (`9.4.1`, `3.9.16`) are not.
 */
const resolution: VersionResolution = {
  isPrefix(spelled) {
    const numeric = spelled.version.slice(spelled.version.search(/\d/));
    return !/^\d+\.\d+\.\d+/.test(numeric);
  },
  query: (spelled) => ({ command: 'asdf', args: ['latest', spelled.name, spelled.version] }),
  parse(result, spelled) {
    // A non-zero exit is asdf saying "no compatible versions" — an
    // outcome, not a defect, so the caller falls back rather than
    // stopping.
    if (result.status !== 0) return undefined;
    const named = result.stdout.trim().split('\n')[0]?.trim() ?? '';
    // Guard against a plugin that echoes something else entirely: a
    // resolved version must still answer the prefix that asked for it.
    return answers(named, spelled.version) ? named : undefined;
  },
  fromConfig(spelled, read) {
    const existing = read(CONFIG_PATH);
    const current = existing === undefined ? undefined : configured(spelled.name, existing);
    return current !== undefined && answers(current, spelled.version) ? current : undefined;
  },
};

/** The asdf record. */
export const asdfProvider: ToolchainProvider = {
  id: 'asdf',
  label: 'asdf — .tool-versions, the format mise reads too',
  covers: TOOLCHAIN_TOOLS,
  spell,
  render(needs, _read, resolved: ResolvedSpellings = new Map()) {
    const entries = needs
      .map((need) => {
        const spelled = spell(need);
        // The concrete version when the engine got one; the prefix
        // otherwise, which is what N.2 guarantees renders regardless.
        return `${spelled.name} ${resolved.get(need.tool) ?? spelled.version}\n`;
      })
      .join('');
    return [{ path: CONFIG_PATH, content: `${CONFIG_HEADER}\n${entries}` }];
  },
  probe: { command: 'asdf', args: ['--version'] },
  install(needs) {
    const plugins: ProviderInvocation[] = [...new Set(needs.map((need) => spell(need).name))].map(
      (plugin) => ({
        command: 'asdf',
        args: ['plugin', 'add', plugin],
        // asdf reports an already-added plugin as a failure; the
        // install that follows is where a genuinely missing plugin
        // surfaces.
        tolerateFailure: true,
      }),
    );
    return [...plugins, { command: 'asdf', args: ['install'] }];
  },
  status: { command: 'asdf', args: ['list'] },
  parseStatus(result: ProcessResult, spelled) {
    // A non-zero exit is data here, not a failure: `asdf list` says
    // "No plugins installed" that way, which is precisely "nothing is
    // satisfied" rather than "the manager could not be asked".
    let plugin: string | undefined;
    const installed = new Map<string, string[]>();
    for (const line of result.stdout.split('\n')) {
      if (line.trim().length === 0) continue;
      if (/^\S/.test(line)) {
        plugin = line.trim();
        installed.set(plugin, []);
        continue;
      }
      // Indented: one installed version, the active one marked '*'.
      if (plugin !== undefined) installed.get(plugin)?.push(line.trim().replace(/^\*/, ''));
    }
    return new Map(
      spelled.map((need) => [
        need.name,
        (installed.get(need.name) ?? []).some((version) => answers(version, need.version)),
      ]),
    );
  },
  bootstrap:
    'asdf is not installed.\n' +
    'Bootstrap it with:  brew install asdf   (or your package manager)\n' +
    '(other install methods: https://asdf-vm.com/guide/getting-started.html)',
  resolve: resolution,
};
