/**
 * The mise provider record — the walking-skeleton provider (roadmap
 * N.2), and the default answer on the manager dial. mise covers the
 * whole tool vocabulary, so it heads the choice list on every
 * profile — always a legal choice under the coverage invariant; its native file is
 * `mise.toml`, understood by mise itself and a growing set of IDEs
 * and images; and `mise install` is idempotent by construction,
 * which is what makes `keel toolchain install` re-runnable at any
 * point in a project's life.
 *
 * The one keel-chosen half of a spelling is the JDK distribution:
 * the block pins a major (`25`), mise wants a distribution-qualified
 * version (`temurin-25`). The distribution is registered in
 * `assets/composition/version-pins.json` (`mise-java-distribution`)
 * so the registry stays the single record of keel-chosen spellings;
 * the version halves ride the block, whose pins the currency loop
 * already covers. Every other tool keeps its block name and version
 * verbatim — `gradle = "9.4.1"` is already mise's spelling.
 */

import type { ProcessResult } from '../../contract/ports/process-runner.js';
import { TOOLCHAIN_TOOLS, type ToolchainNeed } from '../../contract/toolchain.js';
import type { SpelledNeed, ToolchainProvider } from './provider.js';

/** The JDK distribution mise spellings qualify the block's major with. */
const JDK_DISTRIBUTION = 'temurin';

const CONFIG_HEADER = `# Generated by keel ('keel toolchain install') from the toolchain block in
# .claude/.keel-manifest.json — edits here are overwritten on the next run.
# After a keel upgrade: 'keel add toolchain --reapply', then re-install.
`;

function spell(need: ToolchainNeed): SpelledNeed {
  return need.tool === 'jdk'
    ? { name: 'java', version: `${JDK_DISTRIBUTION}-${need.version}` }
    : { name: need.tool, version: need.version };
}

function isInstalled(entry: unknown): boolean {
  if (typeof entry !== 'object' || entry === null) return false;
  const shape = entry as { installed?: unknown; install_path?: unknown };
  // Recent mise reports `installed` outright; older outputs only
  // carry an install_path for versions that are actually on disk.
  if (typeof shape.installed === 'boolean') return shape.installed;
  return typeof shape.install_path === 'string' && shape.install_path.length > 0;
}

/** The mise record. */
export const miseProvider: ToolchainProvider = {
  id: 'mise',
  label: 'mise — one manager for every tool in the vocabulary',
  covers: TOOLCHAIN_TOOLS,
  spell,
  render(needs) {
    const entries = needs
      .map(spell)
      .map((spelled) => `${spelled.name} = "${spelled.version}"\n`)
      .join('');
    return [{ path: 'mise.toml', content: `${CONFIG_HEADER}\n[tools]\n${entries}` }];
  },
  probe: { command: 'mise', args: ['--version'] },
  // Trust first: mise refuses an untrusted config in non-interactive
  // runs, and the rendered file is keel's own output. Both steps read
  // the rendered `mise.toml`, so neither depends on the needs.
  install: () => [
    { command: 'mise', args: ['trust'] },
    { command: 'mise', args: ['install'] },
  ],
  status: { command: 'mise', args: ['ls', '--current', '--json'] },
  parseStatus(result: ProcessResult) {
    if (result.status !== 0) {
      const detail = (result.stderr || result.stdout).trim();
      throw new Error(`mise ls exited ${String(result.status)}${detail ? `: ${detail}` : ''}`);
    }
    const parsed: unknown = JSON.parse(result.stdout);
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      throw new Error('expected a JSON object keyed by tool name');
    }
    const statuses = new Map<string, boolean>();
    for (const [name, versions] of Object.entries(parsed)) {
      if (Array.isArray(versions)) statuses.set(name, versions.some(isInstalled));
    }
    return statuses;
  },
  bootstrap:
    'mise is not installed.\n' +
    'Bootstrap it with:  curl https://mise.run | sh\n' +
    '(other install methods: https://mise.jdx.dev/getting-started.html)',
};
