/**
 * The nvm provider record — Node and nothing else, which is exactly
 * why it exists on the dial: it is the manager most Node developers
 * already have, and `.nvmrc` is the file their editors, CI images
 * and teammates already read.
 *
 * Two things make this record unlike mise's and asdf's:
 *
 * - **nvm is a shell function, not a binary.** There is nothing to
 *   spawn, so every invocation goes through a login shell that
 *   sources `nvm.sh` first. That is nvm's own documented usage, not
 *   a keel trick.
 * - **`.nvmrc` holds a bare version and nothing else.** No header
 *   comment, unlike `mise.toml` and `.tool-versions`: the format has
 *   no room for one, and nvm reads the file's first line. The
 *   "generated by keel" note lives in the docs instead.
 *
 * Coverage is `node` **and** `npm`: npm ships with every Node
 * install, so a manager that provisions Node has provisioned npm.
 * pnpm does not ride along, which is what makes nvm alone a legal
 * choice on the npm-tagged TS profiles and only half of one on the
 * pnpm-tagged ones — where the dial offers `nvm+corepack` instead.
 */

import type { ProcessResult } from '../../contract/ports/process-runner.js';
import type { ToolchainNeed } from '../../contract/toolchain.js';
import type { ProviderInvocation, SpelledNeed, ToolchainProvider } from './provider.js';

/** The nvm release the bootstrap guidance points at. */
const NVM_INSTALLER = 'v0.40.6';

/** Runs an nvm command in a shell that has sourced nvm first. */
function shell(nvmCommand: string): ProviderInvocation {
  return {
    command: 'bash',
    args: [
      '-lc',
      `export NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"; [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; ${nvmCommand}`,
    ],
  };
}

function spell(need: ToolchainNeed): SpelledNeed {
  return { name: need.tool, version: need.version };
}

/** Whether an installed version answers the requested one. */
function answers(installed: string, requested: string): boolean {
  return installed === requested || installed.startsWith(`${requested}.`);
}

/** The nvm record. */
export const nvmProvider: ToolchainProvider = {
  id: 'nvm',
  label: 'nvm — .nvmrc, Node only (npm ships with it)',
  covers: ['node', 'npm'],
  spell,
  render(needs) {
    // npm needs no line of its own: it arrives with the Node install
    // nvm performs, and `.nvmrc` names one runtime, not a tool list.
    const node = needs.find((need) => need.tool === 'node');
    return node === undefined ? [] : [{ path: '.nvmrc', content: `${node.version}\n` }];
  },
  probe: shell('nvm --version'),
  // `nvm install` with no argument reads `.nvmrc` from the working
  // directory — the rendered file is the whole instruction.
  install: () => [shell('nvm install')],
  status: shell('nvm ls --no-colors'),
  parseStatus(result: ProcessResult, spelled) {
    const installed = [...result.stdout.matchAll(/\bv(\d[\w.-]*)/g)].map((match) => match[1] ?? '');
    const node = spelled.find((need) => need.name === 'node');
    const satisfied =
      node !== undefined && installed.some((version) => answers(version, node.version));
    // npm's status is node's: nvm installs the two together.
    return new Map(spelled.map((need) => [need.name, satisfied]));
  },
  bootstrap:
    'nvm is not installed (or its shell function is not loaded).\n' +
    `Bootstrap it with:  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_INSTALLER}/install.sh | bash\n` +
    'then open a new shell (nvm is a shell function, not a binary).',
};
