/**
 * The rustup provider record — the Rust ecosystem's own manager, and
 * the thinnest record on the dial by design.
 *
 * `rust-toolchain.toml` is a file rustup honors **natively**: every
 * `cargo`, `rustc` or `rustfmt` invocation inside the directory
 * resolves through it, installing the named toolchain on first use.
 * There is no activation story to write, no shell hook, no
 * `PATH` wiring — which is the whole reason to offer rustup rather
 * than route Rust through a general-purpose manager (mise itself
 * defers to rustup for the Rust toolchain).
 *
 * One spelling decision, and it is keel's: the block records the
 * Rust need as the major the scaffolds' build images pin (`1`),
 * because the emitted projects track the latest stable by
 * construction. rustup has no "series" channel — its channel
 * vocabulary is `stable` / `beta` / `nightly` or a concrete
 * `1.89` / `1.89.0` — and the channel that means "the latest release
 * of the 1.x series" is exactly `stable`. So a bare major spells
 * `stable`, registered in `assets/composition/version-pins.json`
 * (`rustup-stable-channel`) as the keel-chosen half of the spelling;
 * a version carrying a minor is passed through verbatim.
 */

import type { ProcessResult } from '../../contract/ports/process-runner.js';
import type { ToolchainNeed } from '../../contract/toolchain.js';
import type { SpelledNeed, ToolchainProvider } from './provider.js';

/** The channel a bare-major need spells — see the module doc. */
const STABLE_CHANNEL = 'stable';

const CONFIG_HEADER = `# Generated by keel ('keel toolchain install') from the toolchain block in
# .claude/.keel-manifest.json — edits here are overwritten on the next run.
# After a keel upgrade: 'keel add toolchain --reapply', then re-install.
`;

function spell(need: ToolchainNeed): SpelledNeed {
  return {
    name: 'rust',
    version: /^\d+$/.test(need.version) ? STABLE_CHANNEL : need.version,
  };
}

/**
 * Whether an installed toolchain answers the requested channel.
 * `rustup toolchain list` prints target-qualified names
 * (`stable-x86_64-unknown-linux-gnu`, `1.89.0-aarch64-apple-darwin`),
 * so the requested channel is a prefix of the installed name — and a
 * concrete `1.89` is answered by its patch releases.
 */
function answers(installed: string, requested: string): boolean {
  return (
    installed === requested ||
    installed.startsWith(`${requested}-`) ||
    installed.startsWith(`${requested}.`)
  );
}

/** The rustup record. */
export const rustupProvider: ToolchainProvider = {
  id: 'rustup',
  label: 'rustup — rust-toolchain.toml, honored natively by cargo (Rust only)',
  covers: ['rust'],
  spell,
  render(needs) {
    const rust = needs.find((need) => need.tool === 'rust');
    if (rust === undefined) return [];
    return [
      {
        path: 'rust-toolchain.toml',
        content: `${CONFIG_HEADER}\n[toolchain]\nchannel = "${spell(rust).version}"\n`,
      },
    ];
  },
  probe: { command: 'rustup', args: ['--version'] },
  // With no toolchain argument, `rustup toolchain install` installs
  // the *active* toolchain — the one `rust-toolchain.toml` names — so
  // the rendered file is the whole instruction, and re-running it is
  // a no-op.
  install: () => [{ command: 'rustup', args: ['toolchain', 'install'] }],
  status: { command: 'rustup', args: ['toolchain', 'list'] },
  parseStatus(result: ProcessResult, spelled) {
    if (result.status !== 0) {
      const detail = (result.stderr || result.stdout).trim();
      throw new Error(
        `rustup toolchain list exited ${String(result.status)}${detail ? `: ${detail}` : ''}`,
      );
    }
    // "no installed toolchains" is a legal, well-formed answer: it
    // names no toolchain, so nothing matches and nothing is satisfied.
    const installed = result.stdout
      .split('\n')
      .map((line) => line.trim().split(/\s+/)[0] ?? '')
      .filter((name) => name.length > 0);
    return new Map(
      spelled.map((need) => [need.name, installed.some((name) => answers(name, need.version))]),
    );
  },
  bootstrap:
    'rustup is not installed.\n' +
    "Bootstrap it with:  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh\n" +
    '(other install methods: https://rust-lang.github.io/rustup/installation/index.html)',
};
