/**
 * The SDKMAN! provider record — the JVM classic, and the first
 * record on the dial that is *not* universal: it covers the JDK and
 * the two JVM build systems and nothing else, so by the coverage
 * invariant it is offered only where that is the whole declaration —
 * a JVM-only project. On anything carrying a Go, Rust or Node need
 * it is simply never offered, which is the invariant doing its job
 * rather than a special case in the dial.
 *
 * Two things shape the record:
 *
 * - **`sdk` is a shell function, not a binary** — the same story as
 *   nvm's, and reached the same way: every invocation runs through a
 *   login shell that sources `sdkman-init.sh` first. That is
 *   SDKMAN!'s own documented usage, not a keel trick.
 * - **`.sdkmanrc` is the whole instruction.** `sdk env install`
 *   installs every candidate the file names and nothing else, which
 *   is exactly the idempotent, re-runnable action the engine wants;
 *   `sdk env` then activates them without installing anything, which
 *   is what makes the read-only status probe honest.
 *
 * The one keel-chosen half of a spelling is the JDK distribution
 * suffix: the block pins a major (`25`), SDKMAN! wants a
 * distribution-qualified candidate version (`25-tem`). It is
 * registered in `assets/composition/version-pins.json`
 * (`sdkman-java-distribution`) the way mise's and asdf's are; the
 * version halves ride the block, whose pins the currency loop
 * already covers. Gradle and Maven keep their block versions
 * verbatim — `gradle=9.4.1` is already SDKMAN!'s spelling.
 */

import type { ProcessResult } from '../../contract/ports/process-runner.js';
import type { ToolchainNeed, ToolchainTool } from '../../contract/toolchain.js';
import type { ProviderInvocation, SpelledNeed, ToolchainProvider } from './provider.js';

/** The JDK distribution SDKMAN! spellings qualify the block's major with. */
const JDK_DISTRIBUTION = 'tem';

/** The tools SDKMAN! has candidates for — the JVM's, and only those. */
const COVERS: readonly ToolchainTool[] = ['jdk', 'gradle', 'maven'];

/** Tools whose SDKMAN! candidate is not named after the tool. */
const CANDIDATE_NAMES: Partial<Record<ToolchainTool, string>> = { jdk: 'java' };

const CONFIG_HEADER = `# Generated by keel ('keel toolchain install') from the toolchain block in
# .claude/.keel-manifest.json — edits here are overwritten on the next run.
# After a keel upgrade: 'keel add toolchain --reapply', then re-install.
`;

/** Runs an sdk command in a shell that has sourced SDKMAN! first. */
function shell(sdkCommand: string): ProviderInvocation {
  return {
    command: 'bash',
    args: [
      '-lc',
      `export SDKMAN_DIR="\${SDKMAN_DIR:-$HOME/.sdkman}"; ` +
        `[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] && . "$SDKMAN_DIR/bin/sdkman-init.sh"; ${sdkCommand}`,
    ],
  };
}

function spell(need: ToolchainNeed): SpelledNeed {
  const name = CANDIDATE_NAMES[need.tool] ?? need.tool;
  return need.tool === 'jdk'
    ? { name, version: `${need.version}-${JDK_DISTRIBUTION}` }
    : { name, version: need.version };
}

/** One `candidate: version` line of `sdk current`. */
const IN_USE = /^[ \t]*([a-z][\w-]*):[ \t]*(\S+)[^\S\n]*$/gm;

/** The SDKMAN! record. */
export const sdkmanProvider: ToolchainProvider = {
  id: 'sdkman',
  label: 'sdkman — .sdkmanrc, the JVM classic: JDK, Gradle, Maven (JVM-only projects)',
  covers: COVERS,
  spell,
  render(needs) {
    const entries = needs
      .map(spell)
      .map((spelled) => `${spelled.name}=${spelled.version}\n`)
      .join('');
    return [{ path: '.sdkmanrc', content: `${CONFIG_HEADER}\n${entries}` }];
  },
  probe: shell('sdk version'),
  // `sdk env install` installs every candidate `.sdkmanrc` names and
  // nothing else — the rendered file is the whole instruction, so the
  // step does not depend on the needs.
  install: () => [shell('sdk env install')],
  // Read-only: `sdk env` activates what `.sdkmanrc` names *without*
  // installing anything (that is `sdk env install`), so a candidate
  // that is missing simply never shows up in `sdk current`.
  status: shell('sdk env >/dev/null 2>&1; sdk current'),
  parseStatus(result: ProcessResult, spelled) {
    // A non-zero exit is data here, not a failure: `sdk env` says
    // "candidate version is not installed" that way, which is
    // precisely "not satisfied" rather than "the manager could not be
    // asked".
    const inUse = new Map(
      [...result.stdout.matchAll(IN_USE)].map((match) => [match[1] ?? '', match[2] ?? '']),
    );
    return new Map(spelled.map((need) => [need.name, inUse.get(need.name) === need.version]));
  },
  bootstrap:
    'sdkman is not installed (or its shell function is not loaded).\n' +
    'Bootstrap it with:  curl -s "https://get.sdkman.io" | bash\n' +
    'then open a new shell (sdk is a shell function, not a binary).',
};
