FROM gradle:jdk21 AS build
WORKDIR /workspace
COPY . .
RUN gradle build -x test

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/application/rest/executable/build/libs/application-rest-executable-0.1.0-SNAPSHOT.jar /app/app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
