/**
 * The regions of keel's own documentation that are **generated, not
 * written**: the compatibility matrix in `docs/verticals/README.md` and
 * the defaults table in `docs/stacks/README.md`. Each is a projection
 * of the composition grid's verdicts and of the registry, rendered here
 * and held to its committed text by `tests/generated-docs.test.ts`.
 *
 * Both used to be written by hand, and both rotted the way an index
 * nobody checks does: the matrix showed `distribution` and `iac` as
 * addable in a monorepo service after the grid had them refused there,
 * and the defaults table left out `agent-harness` and `code-style`
 * long after every preset installed them. A cell here is what the
 * grid's goldens record, so a verdict that moves is a document that
 * moves, in the same commit, or the guard goes red.
 *
 * **Scenario.** The brownfield and composite grid goldens
 * (`tests/domain/core/composition-grid/`) for every verdict;
 * `keel.dials` for what each preset, product root and service comes
 * with (`included`), on default dials; the registry for the order a
 * preset installs its verticals in. Stacks, verticals, layouts and
 * services are read from those, never listed here, so a preset or a
 * vertical registered tomorrow shows up in both documents on the next
 * regeneration.
 *
 * **Factory.** `installMediator` — the queries read no disk.
 *
 * **Port.** `Mediator.dispatch` (`keel.catalog`, `keel.dials`), and
 * the goldens as the grid's suites wrote them.
 *
 * A region is the text between two sentinel comments,
 * `<!-- generated:<name>:begin -->` and `<!-- generated:<name>:end -->`.
 * Everything outside them is prose someone wrote and survives a
 * regeneration untouched; the file as a whole is then run through
 * prettier, as `pnpm lint` checks it, so the committed bytes are the
 * regenerated bytes.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import type { RepoLayout } from '../../src/domain/contract/commands.js';
import type { Registry } from '../../src/domain/contract/ports/registry.js';
import {
  catalogQuery,
  dialsQuery,
  type DialOptions,
  type VerticalOption,
} from '../../src/domain/contract/queries.js';
import type { Mediator } from '../../src/domain/kernel/mediator.js';
import { UNCOVERED_CODE, WRONG_SCOPE_CODE } from '../../src/domain/core/refusals.js';
import { shippedRegistry } from '../../src/domain/core/registry.js';
import { ENTRYPOINTS, entrypointsLabel } from '../../src/domain/core/stack-wizard.js';
import { expectOk } from './factory.js';

/** The repository root, which every {@link GeneratedRegion.file} is relative to. */
export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

/** The one line that rewrites every generated region from the goldens as committed. */
export const REGENERATE = 'KEEL_UPDATE_GOLDEN=1 pnpm exec vitest run tests/generated-docs.test.ts';

/** Where the grid's suites keep their goldens. */
const GRID_DIR = path.join(REPO_ROOT, 'tests', 'domain', 'core', 'composition-grid');

/** The verdict of a cell that came back Ok, as the goldens spell it. */
const OK = 'ok';

/** The refusal of `keel add` in a directory that holds no keel project. */
const NOT_A_PROJECT = 'keel.not-initialised';

/** What `keel add <vertical>` came back as in one scope, and whether the scope comes with it. */
export interface ScopeFacts {
  /** Vertical id → the golden's verdict: {@link OK} or a refusal's code. */
  readonly verdicts: Readonly<Record<string, string>>;
  /** The verticals `keel.dials` shows as coming with the scope (`included`). */
  readonly included: readonly string[];
}

/** One single-service preset, as the documents read it. */
export interface StackFacts extends ScopeFacts {
  /** The preset's id, as `keel new --stack` takes it. */
  readonly id: string;
  /** Its entrypoints, as {@link ENTRYPOINTS} ids, in that list's order. */
  readonly entrypoints: readonly string[];
  /** The verticals its preset installs, in install order. */
  readonly installs: readonly string[];
}

/** One service of a product preset. */
export interface ServiceFacts {
  /** Where the service sits under the product root, as the preset declares it. */
  readonly path: string;
  /** The single-service preset it is scaffolded from. */
  readonly stack: string;
  /** What the product installs in it on top of that preset's own, in install order. */
  readonly extras: readonly string[];
}

/** A product scaffolded under one repository layout. */
export interface LayoutFacts {
  /** The repository layout, as `--layout` takes it. */
  readonly layout: string;
  /** The product root; null where the layout leaves no keel project there. */
  readonly root: ScopeFacts | null;
  /** Service path → that service's scope. */
  readonly services: Readonly<Record<string, ScopeFacts>>;
}

/** One product preset, as the documents read it. */
export interface ProductFacts {
  /** The product preset's id, as `keel new --stack` takes it. */
  readonly id: string;
  /** The verticals its root installs, in install order. */
  readonly installs: readonly string[];
  readonly services: readonly ServiceFacts[];
  /** One per repository layout the composite grid swept it under. */
  readonly layouts: readonly LayoutFacts[];
}

/** Everything the generated regions are rendered from. */
export interface GridFacts {
  /** Every vertical the catalog offers `keel add`, id-sorted. */
  readonly verticals: readonly string[];
  /** The single-service presets, id-sorted. */
  readonly stacks: readonly StackFacts[];
  /** The product presets, id-sorted. */
  readonly products: readonly ProductFacts[];
}

/**
 * Reads {@link GridFacts} from the committed goldens and from
 * `keel.catalog` and `keel.dials` over `mediator`.
 *
 * A single-service preset's verdicts are the brownfield axis's — `keel
 * add` in its fresh scaffold, which the grid holds to the greenfield
 * `--with` verdict (I5) — and a product's are the composite axis's, at
 * its root and in each service, under each layout that axis swept.
 * A cell the golden does not have is a golden older than the catalog,
 * and fails with the order to regenerate the grid first.
 */
export async function gridFacts(
  mediator: Mediator,
  registry: Registry = shippedRegistry,
): Promise<GridFacts> {
  const catalog = expectOk(await mediator.dispatch(catalogQuery()));
  const brownfield = golden('brownfield');
  const composite = golden('composite');
  const verticals = catalog.verticals.map((vertical) => vertical.id);
  const installs = (id: string): readonly string[] => {
    const stack = registry.stacks().find((candidate) => candidate.id === id);
    if (stack === undefined) throw new Error(`the catalog lists '${id}', the registry does not`);
    return stack.verticals.map((vertical) => vertical.id);
  };
  const verdicts = (axis: Golden, scope: string): Record<string, string> =>
    Object.fromEntries(verticals.map((vertical) => [vertical, axis.verdict(scope, vertical)]));
  const dials = async (stack: string, layout?: string): Promise<DialOptions> =>
    expectOk(
      await mediator.dispatch(
        dialsQuery({
          target: {
            kind: 'new-project',
            stack,
            ...(layout === undefined ? {} : { layout: layout as RepoLayout }),
          },
        }),
      ),
    );

  const stacks: StackFacts[] = [];
  const products: ProductFacts[] = [];
  for (const stack of [...catalog.stacks].sort((a, b) => a.id.localeCompare(b.id))) {
    if (stack.services.length === 0) {
      stacks.push({
        id: stack.id,
        entrypoints: ENTRYPOINTS.filter((entry) => stack.tags.includes(entry.tag)).map(
          (entry) => entry.id,
        ),
        installs: installs(stack.id),
        verdicts: verdicts(brownfield, stack.id),
        included: includedIn((await dials(stack.id)).verticals),
      });
      continue;
    }
    const preset = registry.stacks().find((candidate) => candidate.id === stack.id);
    const services: ServiceFacts[] = stack.services.map((service) => ({
      path: service.path,
      stack: service.stack,
      extras: (
        preset?.services?.find((declared) => declared.path === service.path)?.extraVerticals ?? []
      ).map((vertical) => vertical.id),
    }));
    const layouts: LayoutFacts[] = [];
    for (const layout of composite.layoutsOf(stack.id)) {
      const options = await dials(stack.id, layout);
      const root = verdicts(composite, `${stack.id}/${layout}`);
      layouts.push({
        layout,
        // What the root comes with is what `keel.dials` reads as coming
        // with the product: its own verticals, and what the services
        // that could have it have — where `keel add` at the root is an
        // Ok that adds nothing (the composite grid holds the two equal).
        root: Object.values(root).every((verdict) => verdict === NOT_A_PROJECT)
          ? null
          : { verdicts: root, included: includedIn(options.verticals) },
        services: Object.fromEntries(
          services.map((service) => [
            service.path,
            {
              verdicts: verdicts(composite, `${stack.id}/${layout}/${service.path}`),
              included: includedIn(
                options.services.find((dialled) => dialled.path === service.path)?.verticals ?? [],
              ),
            },
          ]),
        ),
      });
    }
    products.push({ id: stack.id, installs: installs(stack.id), services, layouts });
  }
  return { verticals, stacks, products };
}

function includedIn(options: readonly VerticalOption[]): readonly string[] {
  return options.filter((option) => option.readiness === 'included').map((option) => option.id);
}

/** One grid golden's `keel add` cells, read by scope and vertical. */
interface Golden {
  /** The verdict of `keel add <vertical>` in `scope`; throws when the golden has no such cell. */
  verdict(scope: string, vertical: string): string;
  /** The repository layouts the golden swept `product` under, sorted; throws when none. */
  layoutsOf(product: string): readonly string[];
}

function golden(axis: string): Golden {
  const file = path.join(GRID_DIR, `${axis}.golden.json`);
  const cells = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, string>;
  return {
    verdict(scope, vertical) {
      const verdict = cells[`add:${scope}+${vertical}`];
      if (verdict === undefined) {
        throw new Error(
          `${axis}.golden.json has no cell 'add:${scope}+${vertical}' — regenerate the grid (tests/AGENTS.md → The composition grid), then the docs`,
        );
      }
      return verdict;
    },
    layoutsOf(product) {
      const layouts = new Set<string>();
      for (const cell of Object.keys(cells)) {
        const scope = /^add:([^+]+)\+/.exec(cell)?.[1]?.split('/');
        if (scope?.[0] === product && scope[1] !== undefined) layouts.add(scope[1]);
      }
      if (layouts.size === 0) {
        throw new Error(
          `${axis}.golden.json has no cell for the product '${product}' — regenerate the grid (tests/AGENTS.md → The composition grid), then the docs`,
        );
      }
      return [...layouts].sort();
    },
  };
}

/**
 * What a matrix cell shows, and what the legend says it means — in the
 * order the legend lists them. A refusal under a code with no glyph
 * shows the code itself.
 */
const GLYPHS: readonly { readonly glyph: string; readonly means: string }[] = [
  {
    glyph: '●',
    means:
      'comes with it: `keel new` installs it — in a monorepo service, the product root gives it; at a product root, its services have it',
  },
  { glyph: '➕', means: '`keel add` installs it, with anything it needs first' },
  { glyph: '⛔', means: `refused: nothing keel has installs it there (\`${UNCOVERED_CODE}\`)` },
  {
    glyph: '↪',
    means: `refused there: it belongs in another scope, a service or the repository's root (\`${WRONG_SCOPE_CODE}\`)`,
  },
];

/** The glyph of one verdict. */
function glyphOf(verdict: string, included: boolean, where: string): string {
  if (included) {
    if (verdict !== OK) {
      throw new Error(
        `${where}: keel.dials says it comes with the scope, yet its add is ${verdict}`,
      );
    }
    return '●';
  }
  if (verdict === OK) return '➕';
  if (verdict === UNCOVERED_CODE) return '⛔';
  if (verdict === WRONG_SCOPE_CODE) return '↪';
  return `\`${verdict}\``;
}

/**
 * One scope a matrix column speaks for, named along each dimension a
 * split cell may be read on — the first that decides the cell names it.
 */
interface Member {
  readonly along: readonly Dimension[];
  /** Vertical id → its glyph here. */
  readonly glyphs: Readonly<Record<string, string>>;
}

/** One name of a {@link Member}: `layout` is one of a few, the others one of many. */
interface Dimension {
  readonly kind: 'stack' | 'product' | 'layout';
  readonly name: string;
}

/** One column of the matrix. */
interface Column {
  readonly header: string;
  /** Who the column speaks for, as the list under the table says it. */
  readonly speaksFor: string;
  readonly members: readonly Member[];
}

/**
 * The single-service presets by the entrypoints they are driven from,
 * each set named as the wizard names it (`CLI + HTTP server`): ordered
 * by the last of its entrypoints in {@link ENTRYPOINTS}, then by how
 * many it has — CLI, HTTP server, CLI + HTTP server, Browser SPA.
 */
function shapes(stacks: readonly StackFacts[]): readonly (readonly [string, StackFacts[]])[] {
  const byShape = new Map<string, StackFacts[]>();
  for (const stack of stacks) {
    const key = stack.entrypoints.join('+');
    byShape.set(key, [...(byShape.get(key) ?? []), stack]);
  }
  const rank = (entrypoints: readonly string[]): readonly number[] => {
    const indices = entrypoints.map((id) => ENTRYPOINTS.findIndex((entry) => entry.id === id));
    return [Math.max(...indices), indices.length];
  };
  return [...byShape.values()]
    .sort((a, b) => {
      const [left, right] = [rank(a[0]!.entrypoints), rank(b[0]!.entrypoints)];
      return left[0]! - right[0]! || left[1]! - right[1]!;
    })
    .map((members) => [shapeLabel(members[0]!.entrypoints), members] as const);
}

function shapeLabel(entrypoints: readonly string[]): string {
  if (entrypoints.length === 0) throw new Error('a single-service preset reaches no entrypoint');
  return entrypointsLabel(entrypoints);
}

function columnsOf(facts: GridFacts, verticals: readonly string[]): readonly Column[] {
  const glyphs = (scope: ScopeFacts, where: string): Record<string, string> =>
    Object.fromEntries(
      verticals.map((vertical) => [
        vertical,
        glyphOf(
          scope.verdicts[vertical] ?? '',
          scope.included.includes(vertical),
          `${where} + ${vertical}`,
        ),
      ]),
    );
  const single: Column[] = shapes(facts.stacks).map(([header, stacks]) => ({
    header,
    speaksFor: stacks.map((stack) => code(stack.id)).join(', '),
    members: stacks.map(
      (stack): Member => ({
        along: [{ kind: 'stack', name: code(stack.id) }],
        glyphs: glyphs(stack, stack.id),
      }),
    ),
  }));
  const scoped = (
    header: string,
    pick: (layout: LayoutFacts) => ScopeFacts | null,
    on: (product: ProductFacts) => string | null,
  ): Column | null => {
    const members: Member[] = [];
    const layouts = new Set<string>();
    const products: ProductFacts[] = [];
    for (const product of facts.products) {
      for (const layout of product.layouts) {
        const scope = pick(layout);
        if (scope === null) continue;
        layouts.add(layout.layout);
        if (!products.includes(product)) products.push(product);
        members.push({
          along: [
            { kind: 'layout', name: layout.layout },
            { kind: 'product', name: code(product.id) },
          ],
          glyphs: glyphs(scope, `${product.id}/${layout.layout} ${header}`),
        });
      }
    }
    if (members.length === 0) return null;
    const presets = [...new Set(products.map(on))];
    const listing = products.map((product) => code(product.id)).join(', ');
    const who =
      presets.length > 1
        ? products.map((product) => `${code(product.id)} (${code(on(product) ?? '?')})`).join(', ')
        : presets[0] === null || presets[0] === undefined
          ? listing
          : `${listing}, each on ${code(presets[0])}`;
    const under = [...layouts].sort();
    return {
      header,
      speaksFor: `${who}; under the ${listed(under)} layout${under.length > 1 ? 's' : ''}`,
      members,
    };
  };
  const paths = [
    ...new Set(facts.products.flatMap((product) => product.services.map((s) => s.path))),
  ];
  const product: (Column | null)[] = [
    scoped(
      'Product root',
      (layout) => layout.root,
      () => null,
    ),
    ...paths.map((servicePath) =>
      scoped(
        `Product ${code(`${servicePath}/`)}`,
        (layout) => layout.services[servicePath] ?? null,
        (each) => each.services.find((service) => service.path === servicePath)?.stack ?? null,
      ),
    ),
  ];
  return [...single, ...product.filter((column): column is Column => column !== null)];
}

/**
 * The cell of `vertical` in a column: its one glyph, or — where the
 * column's scopes disagree — each glyph with the scopes showing it,
 * named along the first dimension that decides it. A layout is one of
 * a few, so every one is named (`● monorepo · ➕ polyrepo`); a stack or
 * a product is one of many, so the most common glyph reads as the
 * rest (`➕ \`quarkus-cli\` · ⛔ the rest`). Where no one dimension
 * decides it, each scope is named whole.
 */
function cellOf(members: readonly Member[], vertical: string): string {
  const shown = members.map((member) => member.glyphs[vertical] ?? '');
  if (new Set(shown).size <= 1) return shown[0] ?? '';
  const dimensions = members[0]?.along.length ?? 0;
  for (let index = 0; index < dimensions; index++) {
    const decided = new Map<string, string>();
    let decides = true;
    for (const member of members) {
      const name = member.along[index]!.name;
      const glyph = member.glyphs[vertical] ?? '';
      if ((decided.get(name) ?? glyph) !== glyph) {
        decides = false;
        break;
      }
      decided.set(name, glyph);
    }
    if (decides) return split([...decided], members[0]!.along[index]!.kind === 'layout');
  }
  return split(
    members.map((member) => [
      member.along
        .map((dimension) => dimension.name)
        .reverse()
        .join(' / '),
      member.glyphs[vertical] ?? '',
    ]),
    false,
  );
}

function split(named: readonly (readonly [string, string])[], every: boolean): string {
  const groups = new Map<string, string[]>();
  for (const [name, glyph] of named) groups.set(glyph, [...(groups.get(glyph) ?? []), name]);
  const entries = [...groups];
  const phrase = ([glyph, names]: readonly [string, readonly string[]]): string =>
    `${glyph} ${names.join(', ')}`;
  if (every) return entries.map(phrase).join(' · ');
  const rest = entries.reduce((most, entry) => (entry[1].length > most[1].length ? entry : most));
  return [...entries.filter((entry) => entry !== rest).map(phrase), `${rest[0]} the rest`].join(
    ' · ',
  );
}

/**
 * The compatibility matrix: a row per vertical `keel add` can name, in
 * the order `order` gives them (the catalog table above it), a column
 * per single-service shape and per product scope, the legend it uses
 * and the list of who each column speaks for.
 *
 * Throws when the catalog offers a vertical `order` does not place —
 * a new vertical gets its row in the catalog table first.
 */
export function renderMatrix(facts: GridFacts, order: readonly string[]): string {
  const unplaced = facts.verticals.filter((vertical) => !order.includes(vertical));
  if (unplaced.length > 0) {
    throw new Error(
      `the catalog table in docs/verticals/README.md has no row for ${unplaced.map(code).join(', ')} — add one; the matrix follows its order`,
    );
  }
  const rows = order.filter((vertical) => facts.verticals.includes(vertical));
  const columns = columnsOf(facts, rows);
  const cells = rows.map((vertical) => [
    code(vertical),
    ...columns.map((column) => cellOf(column.members, vertical)),
  ]);
  const used = cells.flatMap((row) => row.slice(1)).join(' ');
  const legend = GLYPHS.filter(({ glyph }) => used.includes(glyph)).map(
    ({ glyph, means }) => `${glyph} ${means}`,
  );
  if (/`keel\./.test(used)) legend.push('`keel.…` refused under the code it shows');
  return [
    legend.join(' ·\n'),
    '',
    table(['Vertical', ...columns.map((column) => column.header)], cells),
    '',
    'Who each column speaks for:',
    '',
    ...columns.map((column) => `- **${column.header}** — ${column.speaksFor}`),
  ].join('\n');
}

/**
 * The defaults table: a row per single-service shape with the verticals
 * its presets install, in install order, then the product root and
 * each product service. Presets of one shape that install different
 * lists get a row each, naming them.
 *
 * Throws when a vertical has no page under `docs/verticals/` to link.
 */
export function renderDefaults(facts: GridFacts): string {
  const rows: string[][] = [];
  const byList = <T>(items: readonly T[], list: (item: T) => readonly string[]): T[][] => {
    const groups = new Map<string, T[]>();
    for (const item of items) {
      const key = list(item).join(',');
      groups.set(key, [...(groups.get(key) ?? []), item]);
    }
    return [...groups.values()];
  };
  for (const [label, stacks] of shapes(facts.stacks)) {
    const groups = byList(stacks, (stack) => stack.installs);
    for (const group of groups) {
      const who = groups.length > 1 ? ` (${group.map((stack) => code(stack.id)).join(', ')})` : '';
      rows.push([`${label}${who}`, links(group[0]!.installs)]);
    }
  }
  const rootLayouts = [
    ...new Set(
      facts.products.flatMap((product) =>
        product.layouts.filter((layout) => layout.root !== null).map((layout) => layout.layout),
      ),
    ),
  ].sort();
  const roots =
    rootLayouts.length === 0 ? [] : byList(facts.products, (product) => product.installs);
  for (const group of roots) {
    const who =
      roots.length > 1 ? ` of ${group.map((product) => code(product.id)).join(', ')}` : '';
    rows.push([`Product root${who} (${listed(rootLayouts)})`, links(group[0]!.installs)]);
  }
  const shapeOf = (stack: string): string => {
    const found = facts.stacks.find((candidate) => candidate.id === stack);
    if (found === undefined)
      throw new Error(`a product service's preset '${stack}' is no single-service preset`);
    return shapeLabel(found.entrypoints);
  };
  const paths = [
    ...new Set(facts.products.flatMap((product) => product.services.map((s) => s.path))),
  ];
  for (const servicePath of paths) {
    const holding = facts.products.filter((product) =>
      product.services.some((service) => service.path === servicePath),
    );
    const serviceOf = (product: ProductFacts): ServiceFacts =>
      product.services.find((service) => service.path === servicePath)!;
    const groups = byList(holding, (product) => [
      shapeOf(serviceOf(product).stack),
      ...serviceOf(product).extras,
    ]);
    for (const group of groups) {
      const service = serviceOf(group[0]!);
      const who =
        groups.length > 1 ? ` of ${group.map((product) => code(product.id)).join(', ')}` : '';
      const extras = service.extras.length > 0 ? `, + ${links(service.extras)}` : '';
      rows.push([
        `Product ${code(`${servicePath}/`)}${who}`,
        `the ${shapeOf(service.stack)} row${extras}`,
      ]);
    }
  }
  return table(['Shape', 'Verticals installed at bootstrap'], rows);
}

/** Each vertical linked to its page, in the order given. */
function links(verticals: readonly string[]): string {
  return verticals
    .map((vertical) => {
      const page = path.join(REPO_ROOT, 'docs', 'verticals', `${vertical}.md`);
      if (!fs.existsSync(page)) throw new Error(`docs/verticals/${vertical}.md does not exist`);
      return `[${code(vertical)}](../verticals/${vertical}.md)`;
    })
    .join(' · ');
}

/**
 * The vertical ids of a catalog table — the rows whose first cell links
 * a vertical's page, `| [\`vcs\`](vcs.md) | …` — in the order written.
 */
export function catalogOrder(text: string): readonly string[] {
  return [...text.matchAll(/^\| \[`([^`]+)`\]\([^)]*\) *\|/gm)].map((hit) => hit[1]!);
}

/** One region of a committed document that a renderer owns. */
export interface GeneratedRegion {
  /** The document, relative to the repository root. */
  readonly file: string;
  /** The `<name>` of its `generated:<name>` sentinels. */
  readonly name: string;
  /** The region's body, from the facts and the document as committed. */
  readonly render: (facts: GridFacts, document: string) => string;
}

/** Every generated region in the repository. */
export const GENERATED: readonly GeneratedRegion[] = [
  {
    file: 'docs/verticals/README.md',
    name: 'compatibility-matrix',
    render: (facts, document) => renderMatrix(facts, catalogOrder(document)),
  },
  {
    file: 'docs/stacks/README.md',
    name: 'stack-defaults',
    render: (facts) => renderDefaults(facts),
  },
];

/**
 * `document` with the body of its `name` region replaced by `body`,
 * under a comment saying where it comes from. Throws unless the region
 * is there exactly once, opened before it is closed.
 */
export function spliceRegion(document: string, name: string, body: string): string {
  const begin = `<!-- generated:${name}:begin -->`;
  const end = `<!-- generated:${name}:end -->`;
  const at = document.indexOf(begin);
  const until = document.indexOf(end);
  if (
    at < 0 ||
    until < at ||
    document.indexOf(begin, at + 1) >= 0 ||
    document.indexOf(end, until + 1) >= 0
  ) {
    throw new Error(`expected one '${begin}' … '${end}' region, in that order`);
  }
  const provenance = `<!-- Generated by tests/support/generated-docs.ts from the registry and the composition grid's goldens: edit the generator, not this region. Regenerate with ${REGENERATE} -->`;
  return `${document.slice(0, at)}${begin}\n${provenance}\n\n${body}\n\n${document.slice(until)}`;
}

/**
 * The whole of `file` as regenerating its `region` writes it: spliced,
 * then formatted as `prettier --check` holds it.
 */
export async function regenerated(
  region: GeneratedRegion,
  facts: GridFacts,
  document: string,
): Promise<string> {
  const file = path.join(REPO_ROOT, region.file);
  const spliced = spliceRegion(document, region.name, region.render(facts, document));
  const options = (await prettier.resolveConfig(file)) ?? {};
  return prettier.format(spliced, { ...options, filepath: file });
}

/** A markdown table; prettier aligns it. */
function table(header: readonly string[], rows: readonly (readonly string[])[]): string {
  const line = (cells: readonly string[]): string => `| ${cells.join(' | ')} |`;
  return [line(header), line(header.map(() => '---')), ...rows.map(line)].join('\n');
}

function code(id: string): string {
  return `\`${id}\``;
}

/** `a`, `a and b`, `a, b and c`. */
function listed(names: readonly string[]): string {
  if (names.length <= 1) return names.join('');
  return `${names.slice(0, -1).join(', ')} and ${names[names.length - 1] ?? ''}`;
}
