/**
 * Tests for the asdf provider record: the plugin names that differ
 * from the block's vocabulary, the rendered `.tool-versions`, the
 * plugin-then-install sequence, and the status parser — the pure
 * half of the record, no ports involved.
 */

import { describe, expect, it } from 'vitest';
import type { ProcessResult } from '../../../src/domain/contract/ports/process-runner.js';
import { TOOLCHAIN_TOOLS } from '../../../src/domain/contract/toolchain.js';
import { asdfProvider } from '../../../src/domain/toolchain/core/asdf.js';

/** asdf owns its file outright — it never reads the project's. */
const absent = (): undefined => undefined;

const ran = (stdout: string, status = 0): ProcessResult => ({ status, stdout, stderr: '' });

describe('the asdf record', () => {
  it('covers the whole tool vocabulary, like mise', () => {
    expect([...asdfProvider.covers].sort()).toEqual([...TOOLCHAIN_TOOLS].sort());
  });

  it('spells tools by plugin name, distribution-qualifying the JDK', () => {
    expect(asdfProvider.spell({ tool: 'jdk', version: '25' })).toEqual({
      name: 'java',
      version: 'temurin-25',
    });
    expect(asdfProvider.spell({ tool: 'node', version: '22' })).toEqual({
      name: 'nodejs',
      version: '22',
    });
    expect(asdfProvider.spell({ tool: 'go', version: '1.25.0' })).toEqual({
      name: 'golang',
      version: '1.25.0',
    });
    expect(asdfProvider.spell({ tool: 'gradle', version: '9.4.1' })).toEqual({
      name: 'gradle',
      version: '9.4.1',
    });
  });

  it('renders .tool-versions with a comment header and one line per need', () => {
    const [config] = asdfProvider.render(
      [
        { tool: 'jdk', version: '25', source: 'jvm-jdk' },
        { tool: 'gradle', version: '9.4.1', source: 'jvm-gradle-wrapper' },
      ],
      absent,
    );

    expect(config?.path).toBe('.tool-versions');
    expect(config?.content.startsWith('# Generated by keel')).toBe(true);
    expect(config?.content).toContain('\njava temurin-25\ngradle 9.4.1\n');
  });

  it('adds a plugin per tool before installing, tolerating an already-added one', () => {
    const steps = asdfProvider.install([
      { tool: 'jdk', version: '25' },
      { tool: 'node', version: '22' },
    ]);

    expect(steps.map((step) => step.args.join(' '))).toEqual([
      'plugin add java',
      'plugin add nodejs',
      'install',
    ]);
    expect(steps.slice(0, 2).every((step) => step.tolerateFailure === true)).toBe(true);
    expect(steps.at(-1)?.tolerateFailure).toBeUndefined();
  });

  it('adds each plugin once, however many needs it serves', () => {
    const steps = asdfProvider.install([
      { tool: 'node', version: '22' },
      { tool: 'npm', version: '10' },
      { tool: 'node', version: '22' },
    ]);
    expect(steps.filter((step) => step.args[0] === 'plugin')).toHaveLength(2);
  });

  it('reads installed versions per plugin, matching a major against its patch', () => {
    const statuses = asdfProvider.parseStatus(
      ran('java\n *temurin-25.0.1+9\ngradle\n  9.4.1\nnodejs\n  20.11.0\n'),
      [
        { name: 'java', version: 'temurin-25' },
        { name: 'gradle', version: '9.4.1' },
        { name: 'nodejs', version: '22' },
        { name: 'pnpm', version: '10.33.0' },
      ],
    );

    expect(statuses.get('java')).toBe(true);
    expect(statuses.get('gradle')).toBe(true);
    // Installed, but not the requested major.
    expect(statuses.get('nodejs')).toBe(false);
    // No plugin at all.
    expect(statuses.get('pnpm')).toBe(false);
  });

  it("treats a failing 'asdf list' as nothing installed — that is what it means", () => {
    const statuses = asdfProvider.parseStatus(ran('', 1), [
      { name: 'java', version: 'temurin-25' },
    ]);
    expect(statuses.get('java')).toBe(false);
  });
});
