/**
 * Tests for the asdf provider record: the plugin names that differ
 * from the block's vocabulary, the rendered `.tool-versions`, the
 * plugin-then-install sequence, and the status parser — the pure
 * half of the record, no ports involved.
 */

import { describe, expect, it } from 'vitest';
import type { ProcessResult } from '../../../src/domain/contract/ports/process-runner.js';
import { TOOLCHAIN_TOOLS } from '../../../src/domain/contract/toolchain.js';
import { asdfProvider } from '../../../src/domain/toolchain/core/asdf.js';

/** asdf owns its file outright — it never reads the project's. */
const absent = (): undefined => undefined;

const ran = (stdout: string, status = 0): ProcessResult => ({ status, stdout, stderr: '' });

describe('the asdf record', () => {
  it('covers the whole tool vocabulary, like mise', () => {
    expect([...asdfProvider.covers].sort()).toEqual([...TOOLCHAIN_TOOLS].sort());
  });

  it('spells tools by plugin name, distribution-qualifying the JDK', () => {
    expect(asdfProvider.spell({ tool: 'jdk', version: '25' })).toEqual({
      name: 'java',
      version: 'temurin-25',
    });
    expect(asdfProvider.spell({ tool: 'node', version: '22' })).toEqual({
      name: 'nodejs',
      version: '22',
    });
    expect(asdfProvider.spell({ tool: 'go', version: '1.25.0' })).toEqual({
      name: 'golang',
      version: '1.25.0',
    });
    expect(asdfProvider.spell({ tool: 'gradle', version: '9.4.1' })).toEqual({
      name: 'gradle',
      version: '9.4.1',
    });
  });

  it('renders .tool-versions with a comment header and one line per need', () => {
    const [config] = asdfProvider.render(
      [
        { tool: 'jdk', version: '25', source: 'jvm-jdk' },
        { tool: 'gradle', version: '9.4.1', source: 'jvm-gradle-wrapper' },
      ],
      absent,
    );

    expect(config?.path).toBe('.tool-versions');
    expect(config?.content.startsWith('# Generated by keel')).toBe(true);
    expect(config?.content).toContain('\njava temurin-25\ngradle 9.4.1\n');
  });

  it('adds a plugin per tool before installing, tolerating an already-added one', () => {
    const steps = asdfProvider.install([
      { tool: 'jdk', version: '25' },
      { tool: 'node', version: '22' },
    ]);

    expect(steps.map((step) => step.args.join(' '))).toEqual([
      'plugin add java',
      'plugin add nodejs',
      'install',
    ]);
    expect(steps.slice(0, 2).every((step) => step.tolerateFailure === true)).toBe(true);
    expect(steps.at(-1)?.tolerateFailure).toBeUndefined();
  });

  it('adds each plugin once, however many needs it serves', () => {
    const steps = asdfProvider.install([
      { tool: 'node', version: '22' },
      { tool: 'npm', version: '10' },
      { tool: 'node', version: '22' },
    ]);
    expect(steps.filter((step) => step.args[0] === 'plugin')).toHaveLength(2);
  });

  it('reads installed versions per plugin, matching a major against its patch', () => {
    const statuses = asdfProvider.parseStatus(
      ran('java\n *temurin-25.0.1+9\ngradle\n  9.4.1\nnodejs\n  20.11.0\n'),
      [
        { name: 'java', version: 'temurin-25' },
        { name: 'gradle', version: '9.4.1' },
        { name: 'nodejs', version: '22' },
        { name: 'pnpm', version: '10.33.0' },
      ],
    );

    expect(statuses.get('java')).toBe(true);
    expect(statuses.get('gradle')).toBe(true);
    // Installed, but not the requested major.
    expect(statuses.get('nodejs')).toBe(false);
    // No plugin at all.
    expect(statuses.get('pnpm')).toBe(false);
  });

  it("treats a failing 'asdf list' as nothing installed — that is what it means", () => {
    const statuses = asdfProvider.parseStatus(ran('', 1), [
      { name: 'java', version: 'temurin-25' },
    ]);
    expect(statuses.get('java')).toBe(false);
  });
});

describe('the asdf record — resolving a prefix', () => {
  const resolve = asdfProvider.resolve;
  if (!resolve) throw new Error('test setup: the asdf record declares a resolution');

  const reads =
    (files: Readonly<Record<string, string>>) =>
    (path: string): string | undefined =>
      files[path];

  it('treats a version short of three components as a prefix, and nothing else', () => {
    // The block pins majors for the JDK and Node; the wrapper pins it
    // carries in full are already exactly what asdf wants.
    expect(resolve.isPrefix({ name: 'java', version: 'temurin-25' })).toBe(true);
    expect(resolve.isPrefix({ name: 'nodejs', version: '22' })).toBe(true);
    expect(resolve.isPrefix({ name: 'golang', version: '1.24' })).toBe(true);
    expect(resolve.isPrefix({ name: 'java', version: 'temurin-25.0.4+7' })).toBe(false);
    expect(resolve.isPrefix({ name: 'gradle', version: '9.4.1' })).toBe(false);
    expect(resolve.isPrefix({ name: 'maven', version: '3.9.16' })).toBe(false);
  });

  it("asks asdf itself — 'asdf latest <plugin> <prefix>'", () => {
    expect(resolve.query({ name: 'java', version: 'temurin-25' })).toEqual({
      command: 'asdf',
      args: ['latest', 'java', 'temurin-25'],
    });
  });

  it('takes the version asdf names', () => {
    expect(resolve.parse(ran('temurin-25.0.4+7\n'), { name: 'java', version: 'temurin-25' })).toBe(
      'temurin-25.0.4+7',
    );
  });

  it('refuses an answer that does not answer the prefix that asked', () => {
    expect(resolve.parse(ran('temurin-21.0.5+11\n'), { name: 'java', version: 'temurin-25' })).toBe(
      undefined,
    );
  });

  it("reads a non-zero exit as 'no compatible version', not as a defect", () => {
    expect(
      resolve.parse(ran('No compatible versions available\n', 1), {
        name: 'java',
        version: 'temurin-25',
      }),
    ).toBe(undefined);
  });

  it('keeps what .tool-versions already carries when it answers the prefix', () => {
    const existing = 'gradle 9.4.1\njava temurin-25.0.4+7\n';

    expect(
      resolve.fromConfig(
        { name: 'java', version: 'temurin-25' },
        reads({ '.tool-versions': existing }),
      ),
    ).toBe('temurin-25.0.4+7');
    // A pin bump moved the series: the old value no longer answers.
    expect(
      resolve.fromConfig(
        { name: 'java', version: 'temurin-26' },
        reads({ '.tool-versions': existing }),
      ),
    ).toBe(undefined);
    expect(resolve.fromConfig({ name: 'java', version: 'temurin-25' }, reads({}))).toBe(undefined);
  });

  it('renders the resolved version where the engine got one, the prefix where it did not', () => {
    const needs = [
      { tool: 'jdk', version: '25' },
      { tool: 'node', version: '22' },
    ] as const;

    const [config] = asdfProvider.render(
      [...needs],
      absent,
      new Map([['jdk', 'temurin-25.0.4+7']]),
    );

    expect(config?.content).toContain('java temurin-25.0.4+7\n');
    expect(config?.content).toContain('nodejs 22\n');
  });
});
