/**
 * Tests for the mise provider record: the coverage set, the version
 * spellings, the rendered native file, and the status parser — the
 * pure half of the engine, no ports involved.
 */

import { describe, expect, it } from 'vitest';
import { TOOLCHAIN_TOOLS } from '../../../src/domain/contract/toolchain.js';
import { miseProvider } from '../../../src/domain/toolchain/core/mise.js';

describe('the mise record', () => {
  it('covers the whole tool vocabulary — always a legal choice under the coverage invariant', () => {
    expect([...miseProvider.covers].sort()).toEqual([...TOOLCHAIN_TOOLS].sort());
  });

  it('spells the JDK distribution-qualified and every other tool verbatim', () => {
    expect(miseProvider.spell({ tool: 'jdk', version: '25' })).toEqual({
      name: 'java',
      version: 'temurin-25',
    });
    for (const tool of TOOLCHAIN_TOOLS.filter((t) => t !== 'jdk')) {
      expect(miseProvider.spell({ tool, version: '1.2.3' })).toEqual({
        name: tool,
        version: '1.2.3',
      });
    }
  });

  it('renders mise.toml with a generated-by header and one line per need, in block order', () => {
    const config = miseProvider.render([
      { tool: 'jdk', version: '25', source: 'jvm-jdk' },
      { tool: 'gradle', version: '9.4.1', source: 'jvm-gradle-wrapper' },
    ]);

    expect(config.path).toBe('mise.toml');
    expect(config.content.startsWith('# Generated by keel')).toBe(true);
    expect(config.content).toContain('\n[tools]\njava = "temurin-25"\ngradle = "9.4.1"\n');
  });

  it('renders an empty tools table for an empty needs list', () => {
    const config = miseProvider.render([]);
    expect(config.content.endsWith('\n[tools]\n')).toBe(true);
  });

  it('parses installed-or-not per tool from mise ls output', () => {
    const statuses = miseProvider.parseStatus(
      JSON.stringify({
        java: [{ version: 'temurin-25.0.1', installed: true, active: true }],
        gradle: [{ version: '9.4.1', installed: false }],
        node: [{ version: '22.11.0', install_path: '/home/u/.local/share/mise/installs/node' }],
        pnpm: [{ version: '10.33.0' }],
      }),
    );

    expect(statuses.get('java')).toBe(true);
    expect(statuses.get('gradle')).toBe(false);
    // No `installed` field: an install_path is the older signal.
    expect(statuses.get('node')).toBe(true);
    expect(statuses.get('pnpm')).toBe(false);
  });

  it('throws on output that is not a tool map', () => {
    expect(() => miseProvider.parseStatus('[]')).toThrow(/tool name/);
    expect(() => miseProvider.parseStatus('not json')).toThrow();
  });
});
