/**
 * Tests for the rustup provider record: the Rust-only coverage, the
 * `rust-toolchain.toml` cargo honors natively, the bare-major →
 * `stable` channel spelling, and the status parser over
 * `rustup toolchain list`.
 */

import { describe, expect, it } from 'vitest';
import type { ProcessResult } from '../../../src/domain/contract/ports/process-runner.js';
import { rustupProvider } from '../../../src/domain/toolchain/core/rustup.js';

const absent = (): undefined => undefined;

const ran = (stdout: string, status = 0): ProcessResult => ({ status, stdout, stderr: '' });

describe('the rustup record', () => {
  it('covers rust and nothing else', () => {
    expect([...rustupProvider.covers]).toEqual(['rust']);
  });

  it('spells a bare major as the stable channel — rustup has no series channel', () => {
    expect(rustupProvider.spell({ tool: 'rust', version: '1' })).toEqual({
      name: 'rust',
      version: 'stable',
    });
  });

  it('passes a version carrying a minor through verbatim', () => {
    expect(rustupProvider.spell({ tool: 'rust', version: '1.89.0' }).version).toBe('1.89.0');
  });

  it('renders rust-toolchain.toml — the file cargo resolves through with no activation', () => {
    const [config] = rustupProvider.render(
      [{ tool: 'rust', version: '1', source: 'image-rust' }],
      absent,
    );

    expect(config?.path).toBe('rust-toolchain.toml');
    expect(config?.content).toContain('# Generated by keel');
    expect(config?.content).toContain('[toolchain]\nchannel = "stable"\n');
  });

  it('renders nothing when no Rust need was assigned to it', () => {
    expect(rustupProvider.render([], absent)).toEqual([]);
  });

  it('installs the active toolchain — the rendered file names it', () => {
    expect(rustupProvider.install([])).toEqual([
      { command: 'rustup', args: ['toolchain', 'install'] },
    ]);
  });

  it('reads the installed toolchains out of rustup toolchain list, past the host triple', () => {
    const listing = '1.88.0-x86_64-unknown-linux-gnu\nstable-x86_64-unknown-linux-gnu (default)\n';

    expect(
      rustupProvider.parseStatus(ran(listing), [{ name: 'rust', version: 'stable' }]).get('rust'),
    ).toBe(true);
    expect(
      rustupProvider.parseStatus(ran(listing), [{ name: 'rust', version: '1.88' }]).get('rust'),
    ).toBe(true);
    expect(
      rustupProvider.parseStatus(ran(listing), [{ name: 'rust', version: 'nightly' }]).get('rust'),
    ).toBe(false);
  });

  it('reports nothing satisfied when rustup names no toolchain', () => {
    const statuses = rustupProvider.parseStatus(ran('no installed toolchains\n'), [
      { name: 'rust', version: 'stable' },
    ]);
    expect(statuses.get('rust')).toBe(false);
  });

  it('throws on a failed listing rather than guessing', () => {
    expect(() =>
      rustupProvider.parseStatus({ status: 1, stdout: '', stderr: 'boom' }, [
        { name: 'rust', version: 'stable' },
      ]),
    ).toThrow(/exited 1: boom/);
  });
});
