/**
 * Tests for the SDKMAN! provider record: the JVM-only coverage that
 * the dial turns into "offered on JVM-only projects", the rendered
 * `.sdkmanrc`, the shell-function invocations, and the status parser
 * over `sdk current`.
 */

import { describe, expect, it } from 'vitest';
import type { ProcessResult } from '../../../src/domain/contract/ports/process-runner.js';
import { sdkmanProvider } from '../../../src/domain/toolchain/core/sdkman.js';

const absent = (): undefined => undefined;

const ran = (stdout: string, status = 0): ProcessResult => ({ status, stdout, stderr: '' });

const JVM_NEEDS = [
  { tool: 'gradle', version: '9.4.1', source: 'jvm-gradle-wrapper' },
  { tool: 'jdk', version: '25', source: 'jvm-jdk' },
] as const;

describe('the sdkman record', () => {
  it('covers the JVM tools and nothing else — which is what keeps it JVM-only', () => {
    expect([...sdkmanProvider.covers].sort()).toEqual(['gradle', 'jdk', 'maven']);
  });

  it('renders .sdkmanrc as key=value lines, in block order, under a keel header', () => {
    const [config] = sdkmanProvider.render([...JVM_NEEDS], absent);

    expect(config?.path).toBe('.sdkmanrc');
    expect(config?.content).toContain('# Generated by keel');
    expect(config?.content.trimEnd().split('\n').slice(-2)).toEqual([
      'gradle=9.4.1',
      'java=25-tem',
    ]);
  });

  it('qualifies the JDK major with the distribution, and passes everything else through', () => {
    expect(sdkmanProvider.spell({ tool: 'jdk', version: '25' })).toEqual({
      name: 'java',
      version: '25-tem',
    });
    expect(sdkmanProvider.spell({ tool: 'maven', version: '3.9.16' })).toEqual({
      name: 'maven',
      version: '3.9.16',
    });
  });

  it('reaches sdk through a login shell — it is a shell function, not a binary', () => {
    for (const invocation of [
      sdkmanProvider.probe,
      sdkmanProvider.status,
      ...sdkmanProvider.install([...JVM_NEEDS]),
    ]) {
      expect(invocation.command).toBe('bash');
      expect(invocation.args[0]).toBe('-lc');
      expect(invocation.args[1]).toContain('sdkman-init.sh');
    }
  });

  it("installs with 'sdk env install' — the rendered file is the whole instruction", () => {
    const steps = sdkmanProvider.install([...JVM_NEEDS]);
    expect(steps).toHaveLength(1);
    expect(steps[0]?.args[1]).toContain('sdk env install');
  });

  it('asks read-only: sdk env activates, it never installs', () => {
    expect(sdkmanProvider.status.args[1]).toContain('sdk current');
    expect(sdkmanProvider.status.args[1]).not.toContain('sdk env install');
  });

  it('reads the candidates in use out of sdk current', () => {
    const listing = 'Using:\n\njava: 25-tem\ngradle: 9.4.1\n';

    const statuses = sdkmanProvider.parseStatus(ran(listing), [
      { name: 'java', version: '25-tem' },
      { name: 'gradle', version: '9.4.1' },
    ]);

    expect(statuses.get('java')).toBe(true);
    expect(statuses.get('gradle')).toBe(true);
  });

  it('reports a candidate in use at another version as missing', () => {
    const statuses = sdkmanProvider.parseStatus(ran('Using:\n\njava: 21-tem\n'), [
      { name: 'java', version: '25-tem' },
    ]);
    expect(statuses.get('java')).toBe(false);
  });

  it("treats sdk env's refusal as data — nothing in use means nothing satisfied", () => {
    const statuses = sdkmanProvider.parseStatus(
      ran('Stop! Candidate version is not installed.\n', 1),
      [{ name: 'java', version: '25-tem' }],
    );
    expect(statuses.get('java')).toBe(false);
  });
});
