/**
 * Tests for the SDKMAN! provider record: the JVM-only coverage that
 * the dial turns into "offered on JVM-only projects", the rendered
 * `.sdkmanrc`, the shell-function invocations, and the status parser
 * over `sdk current`.
 */

import { describe, expect, it } from 'vitest';
import type { ProcessResult } from '../../../src/domain/contract/ports/process-runner.js';
import { sdkmanProvider } from '../../../src/domain/toolchain/core/sdkman.js';

const absent = (): undefined => undefined;

const ran = (stdout: string, status = 0): ProcessResult => ({ status, stdout, stderr: '' });

const JVM_NEEDS = [
  { tool: 'gradle', version: '9.4.1', source: 'jvm-gradle-wrapper' },
  { tool: 'jdk', version: '25', source: 'jvm-jdk' },
] as const;

describe('the sdkman record', () => {
  it('covers the JVM tools and nothing else — which is what keeps it JVM-only', () => {
    expect([...sdkmanProvider.covers].sort()).toEqual(['gradle', 'jdk', 'maven']);
  });

  it('renders .sdkmanrc as key=value lines, in block order, under a keel header', () => {
    const [config] = sdkmanProvider.render([...JVM_NEEDS], absent);

    expect(config?.path).toBe('.sdkmanrc');
    expect(config?.content).toContain('# Generated by keel');
    expect(config?.content.trimEnd().split('\n').slice(-2)).toEqual([
      'gradle=9.4.1',
      'java=25-tem',
    ]);
  });

  it('qualifies the JDK major with the distribution, and passes everything else through', () => {
    expect(sdkmanProvider.spell({ tool: 'jdk', version: '25' })).toEqual({
      name: 'java',
      version: '25-tem',
    });
    expect(sdkmanProvider.spell({ tool: 'maven', version: '3.9.16' })).toEqual({
      name: 'maven',
      version: '3.9.16',
    });
  });

  it('reaches sdk through a login shell — it is a shell function, not a binary', () => {
    for (const invocation of [
      sdkmanProvider.probe,
      sdkmanProvider.status,
      ...sdkmanProvider.install([...JVM_NEEDS]),
    ]) {
      expect(invocation.command).toBe('bash');
      expect(invocation.args[0]).toBe('-lc');
      expect(invocation.args[1]).toContain('sdkman-init.sh');
    }
  });

  it("installs with 'sdk env install' — the rendered file is the whole instruction", () => {
    const steps = sdkmanProvider.install([...JVM_NEEDS]);
    expect(steps).toHaveLength(1);
    expect(steps[0]?.args[1]).toContain('sdk env install');
  });

  it('asks read-only: sdk env activates, it never installs', () => {
    expect(sdkmanProvider.status.args[1]).toContain('sdk current');
    expect(sdkmanProvider.status.args[1]).not.toContain('sdk env install');
  });

  it('reads the candidates in use out of sdk current', () => {
    const listing = 'Using:\n\njava: 25-tem\ngradle: 9.4.1\n';

    const statuses = sdkmanProvider.parseStatus(ran(listing), [
      { name: 'java', version: '25-tem' },
      { name: 'gradle', version: '9.4.1' },
    ]);

    expect(statuses.get('java')).toBe(true);
    expect(statuses.get('gradle')).toBe(true);
  });

  it('reports a candidate in use at another version as missing', () => {
    const statuses = sdkmanProvider.parseStatus(ran('Using:\n\njava: 21-tem\n'), [
      { name: 'java', version: '25-tem' },
    ]);
    expect(statuses.get('java')).toBe(false);
  });

  it("treats sdk env's refusal as data — nothing in use means nothing satisfied", () => {
    const statuses = sdkmanProvider.parseStatus(
      ran('Stop! Candidate version is not installed.\n', 1),
      [{ name: 'java', version: '25-tem' }],
    );
    expect(statuses.get('java')).toBe(false);
  });
});

describe('the sdkman record — resolving a prefix', () => {
  const resolve = sdkmanProvider.resolve;
  if (!resolve) throw new Error('test setup: the sdkman record declares a resolution');

  const reads =
    (files: Readonly<Record<string, string>>) =>
    (path: string): string | undefined =>
      files[path];

  /** `sdk list java` as SDKMAN! prints it, vendor by vendor. */
  const LISTING = [
    '================================================================================',
    'Available Java Versions for Linux 64bit',
    '================================================================================',
    ' Vendor        | Use | Version      | Dist    | Status     | Identifier',
    '--------------------------------------------------------------------------------',
    ' Temurin       |     | 25.0.4       | tem     |            | 25.0.4-tem',
    '               |     | 21.0.5       | tem     | installed  | 21.0.5-tem',
    ' Zulu          |     | 25.0.2       | zulu    |            | 25.0.2-zulu',
    '',
  ].join('\n');

  it('calls only a bare major a prefix — every other identifier is already exact', () => {
    expect(resolve.isPrefix({ name: 'java', version: '25-tem' })).toBe(true);
    expect(resolve.isPrefix({ name: 'java', version: '25.0.4-tem' })).toBe(false);
    expect(resolve.isPrefix({ name: 'gradle', version: '9.4.1' })).toBe(false);
    expect(resolve.isPrefix({ name: 'maven', version: '3.9.16' })).toBe(false);
  });

  it('asks through the same login shell every other sdk call goes through', () => {
    const query = resolve.query({ name: 'java', version: '25-tem' });
    expect(query.command).toBe('bash');
    expect(query.args[1]).toContain('sdkman-init.sh');
    expect(query.args[1]).toContain('sdk list java');
  });

  it('takes the newest identifier carrying the major and the distribution', () => {
    expect(resolve.parse(ran(LISTING), { name: 'java', version: '25-tem' })).toBe('25.0.4-tem');
  });

  it("does not mistake another vendor's build of the same major for it", () => {
    expect(resolve.parse(ran(LISTING), { name: 'java', version: '25-zulu' })).toBe('25.0.2-zulu');
    expect(resolve.parse(ran(LISTING), { name: 'java', version: '17-tem' })).toBe(undefined);
  });

  it('names nothing when the listing could not be read', () => {
    expect(resolve.parse(ran('', 1), { name: 'java', version: '25-tem' })).toBe(undefined);
  });

  it('keeps what .sdkmanrc already carries when it answers the major', () => {
    const existing = 'gradle=9.4.1\njava=25.0.4-tem\n';

    expect(
      resolve.fromConfig({ name: 'java', version: '25-tem' }, reads({ '.sdkmanrc': existing })),
    ).toBe('25.0.4-tem');
    expect(
      resolve.fromConfig({ name: 'java', version: '26-tem' }, reads({ '.sdkmanrc': existing })),
    ).toBe(undefined);
    expect(resolve.fromConfig({ name: 'java', version: '25-tem' }, reads({}))).toBe(undefined);
  });

  it('renders the resolved identifier, which is the only kind sdk env install takes', () => {
    const [config] = sdkmanProvider.render(
      [...JVM_NEEDS],
      absent,
      new Map([['jdk', '25.0.4-tem']]),
    );

    expect(config?.content).toContain('java=25.0.4-tem\n');
    expect(config?.content).toContain('gradle=9.4.1\n');
  });
});
